server:
  port: 8443
  servlet:
    context-path: /
spring:
  velocity:
    suffix: ".html"
  datasource:
    url: jdbc:mysql://47.103.118.92:3306/meiya?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: meiahgot
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 47.103.118.92
    username: admin
    password: 123456
    port: 5672
    publisher-confirms: true
    publisher-returns: true

    template:
      mandatory=true:
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 10
        prefetch: 2


spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
mybatis:
  config-location: classpath:mybatis-config.xml

